"""Generate fixtures/mock_extraction_doctored.json from the clean fixture.

The doctored document is the 2:30 demo beat (spec section 10). Keeping it as a
declared diff rather than a hand-edited copy means (a) the two fixtures can
never drift apart, and (b) we can say out loud exactly what we tampered with.

Two tampering modes, one per UNVERIFIED trigger in 4.2:
  1. A corrupted figure  -> the balance sheet identity fails -> quarantine.
  2. A missing bbox      -> the figure has no traceable source -> quarantine.

Run:  python scripts/make_doctored.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "fixtures" / "mock_extraction.json"
DST = ROOT / "fixtures" / "mock_extraction_doctored.json"

# canonical_key -> doctored value. ONE DIGIT changed, the way a real tampered
# or mis-extracted statement looks - the leading 8 becomes a 9.
#
# Note the size of the edit matters. The identity check runs at a 1% tolerance,
# so a small tamper (853,283,605 -> 858,283,605, 0.59%) would slip through by
# design; rounding in published accounts has to be absorbed somewhere. Pick an
# edit big enough to clear the tolerance, and say so out loud in the demo
# rather than pretending the engine catches every possible edit.
CORRUPT_VALUES = {
    "total_assets": 953_283_605,   # was 853,283,605; identity now off by 100m (11.7%)
}

# canonical_keys whose bbox we blank, simulating a reverse-lookup miss.
DROP_BBOX = {"inventory"}


def main() -> None:
    doc = json.loads(SRC.read_text(encoding="utf-8"))

    doc["_note"] = (
        "SYNTHETIC + DELIBERATELY DOCTORED. Generated by scripts/make_doctored.py. "
        f"Corrupted values: {CORRUPT_VALUES}. Blanked bboxes: {sorted(DROP_BBOX)}. "
        "Used in the demo to prove the reconciliation engine catches tampering."
    )
    doc["entity"] = doc["entity"] + " (doctored copy)"

    for item in doc["line_items"]:
        key = item["canonical_key"]
        if key in CORRUPT_VALUES:
            item["value"] = CORRUPT_VALUES[key]
        if key in DROP_BBOX:
            item["bbox"] = None

    DST.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
