-- Payment records are written by the trusted FastAPI backend over a private
-- PostgreSQL connection. The table is still protected because Supabase
-- exposes public schema objects through its Data API when grants allow it.
create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    resource_key text not null,
    caller_id text,
    verify_hash char(64) not null,
    expected_memo varchar(256) not null,
    expected_amount_base_units bigint not null check (expected_amount_base_units > 0),
    expected_mint text not null,
    expected_recipient text not null,
    network text not null check (network = 'devnet'),
    transaction_signature text not null unique,
    payer_wallet text not null,
    commitment text not null,
    slot bigint,
    block_time bigint,
    status text not null default 'verified' check (status = 'verified'),
    created_at timestamptz not null default timezone('utc', now()),
    verified_at timestamptz not null default timezone('utc', now()),
    unique (resource_key, verify_hash),
    constraint payments_verify_hash_hex check (verify_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists payments_resource_idx
    on public.payments (resource_key, verify_hash)
    where status = 'verified';

alter table public.payments enable row level security;
revoke all on table public.payments from anon, authenticated;
